import { z } from "zod";
import type {
  PostalCareerLevel,
  PostalLawArea,
  PostalQuestionFormat,
  PostalQuestionReviewStatus,
  PostalRuleQuestion,
  PostalRulesExam,
} from "@/types";

export type { PostalCareerLevel, PostalLawArea, PostalQuestionFormat, PostalQuestionReviewStatus, PostalRuleQuestion };

export const postalCareerLevels: { value: PostalCareerLevel; label: string }[] = [
  { value: "professional_2_to_1", label: "專業職（二）晉升專業職（一）" },
  { value: "professional_1_to_operations", label: "專業職（一）晉升營運職" },
];

export const postalQuestionFormats: { value: PostalQuestionFormat; label: string }[] = [
  { value: "single_choice", label: "單選題" },
  { value: "short_answer", label: "簡答題" },
  { value: "case_analysis", label: "申論題" },
  { value: "fill_blank", label: "填空題" },
];

export const postalLawAreas = ["郵政法", "郵政儲金匯兌法", "簡易人壽保險法", "郵件處理規則", "郵務營業規章"] as const;

export const usablePostalReviewStatuses: PostalQuestionReviewStatus[] = ["approved", "auto_reviewed"];

export const postalRuleQuestionSchema = z.object({
  career_level: z.enum(["professional_2_to_1", "professional_1_to_operations"]),
  question_format: z.enum(["single_choice", "short_answer", "case_analysis", "fill_blank"]),
  law_area: z.enum(postalLawAreas),
  difficulty: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  question: z.string().min(8),
  options: z
    .object({
      A: z.string().min(1),
      B: z.string().min(1),
      C: z.string().min(1),
      D: z.string().min(1),
    })
    .nullable(),
  answer: z.string().min(1),
  explanation: z.string().min(8),
  source_articles: z
    .array(
      z.object({
        law_name: z.enum(postalLawAreas),
        article_no: z.string().min(1),
        note: z.string().min(1),
      }),
    )
    .min(1),
  tags: z.array(z.string()).default([]),
  source_type: z.enum(["seed", "ai_generated_pending_review", "ai_generated_reviewed"]).default("ai_generated_pending_review"),
  review_status: z.enum(["pending", "auto_reviewed", "approved", "rejected", "needs_edit"]).default("pending"),
});

export const postalGeneratedQuestionsSchema = z.object({
  questions: z.array(postalRuleQuestionSchema).min(1).max(20),
});

export function validatePostalQuestion(question: PostalRuleQuestion) {
  const errors: string[] = [];

  if (!postalLawAreas.includes(question.law_area)) errors.push("法規分類不在允許清單內。");

  if (question.question_format === "single_choice") {
    if (!question.options) {
      errors.push("單選題必須提供 A-D 四個選項。");
    } else {
      const values = Object.values(question.options).map((item) => item.trim());
      const unique = new Set(values);
      if (values.some((item) => item.length < 1)) errors.push("選項不得為空。");
      if (unique.size < 4) errors.push("選項內容不可重複。");
    }
    if (!["A", "B", "C", "D"].includes(question.answer.trim().toUpperCase())) {
      errors.push("單選題答案必須為 A、B、C 或 D。");
    }
  }

  if (question.question.length < 12) errors.push("題目過短，可能無法形成有效測驗。");
  if (question.explanation.length < 20) errors.push("解析過短，無法支撐答案。");
  if (!question.source_articles.length) errors.push("必須提供法規來源或校對註記。");

  for (const source of question.source_articles) {
    if (!postalLawAreas.includes(source.law_name)) {
      errors.push(`來源法規分類錯誤：${source.law_name}`);
    }
    if (!source.note.trim()) errors.push("來源註記不得為空。");
  }

  return errors;
}

export function getAutoReviewStatus(question: PostalRuleQuestion): PostalQuestionReviewStatus {
  return validatePostalQuestion(question).length ? "needs_edit" : "auto_reviewed";
}

const commonSourceNote = "基礎題庫題，正式考前仍建議依最新公告法規人工校對。";

function choice(input: {
  id?: string;
  career_level?: PostalCareerLevel;
  law_area: PostalLawArea;
  difficulty?: 1 | 2 | 3;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  answer: "A" | "B" | "C" | "D";
  explanation: string;
  article_no?: string;
  tags?: string[];
}): PostalRuleQuestion {
  return {
    id: input.id,
    career_level: input.career_level ?? "professional_2_to_1",
    question_format: "single_choice",
    law_area: input.law_area,
    difficulty: input.difficulty ?? 2,
    question: input.question,
    options: input.options,
    answer: input.answer,
    explanation: input.explanation,
    source_articles: [{ law_name: input.law_area, article_no: input.article_no ?? "依最新法規校對", note: commonSourceNote }],
    tags: input.tags ?? [input.law_area],
    source_type: "seed",
    review_status: "approved",
  };
}

const approvedReviewQuestionsV1: PostalRuleQuestion[] = [
  choice({
    law_area: "郵政法",
    question: "關於郵件秘密之保護，下列何者最符合郵政法之規範目的？",
    options: {
      A: "郵件處理人員不得無正當理由拆閱或洩漏郵件內容",
      B: "郵件一經交寄即成為郵局所有",
      C: "郵件內容可供任何第三人查詢",
      D: "郵件秘密只保護包裹，不保護信函",
    },
    answer: "A",
    explanation: "郵件秘密保護重點在於郵件處理過程中不得任意拆閱、洩漏或不當處理郵件內容。",
    tags: ["審題稿v1", "郵政法", "郵件秘密"],
  }),
  choice({
    law_area: "郵政法",
    question: "民間業者未經授權使用容易使人誤認為郵政機構之名稱招攬信件遞送，最可能涉及何種問題？",
    options: {
      A: "郵政名稱或專營秩序之管制",
      B: "簡易人壽保險之受益人指定",
      C: "郵政儲金之利息計算",
      D: "郵件封面書寫格式",
    },
    answer: "A",
    explanation: "未經授權使用容易使人誤認郵政機構之名稱，核心爭點在郵政制度、名稱識別及專營秩序保護。",
    tags: ["審題稿v1", "郵政法", "專營", "名稱"],
  }),
  choice({
    law_area: "郵政法",
    question: "下列何者最能說明郵政服務之公共性？",
    options: {
      A: "郵政服務須兼顧普遍服務、郵件安全與民眾通信需求",
      B: "郵政服務只重視營利，不受法規限制",
      C: "郵政服務完全排除民眾申訴",
      D: "郵政服務只處理商業包裹",
    },
    answer: "A",
    explanation: "郵政服務兼具公共服務性質，重點包括普遍服務、郵件安全、通信需求與制度信賴。",
    tags: ["審題稿v1", "郵政法", "公共性"],
  }),
  choice({
    law_area: "郵件處理規則",
    question: "寄件人交寄郵件時，封面資料應如何處理較為適當？",
    options: {
      A: "應書明足以辨識收件人及地址之資料",
      B: "地址空白仍應一律投遞",
      C: "收件人資料不得記載於封面",
      D: "封面資料是否正確與投遞無關",
    },
    answer: "A",
    explanation: "郵件封面資料須足以辨識收件人與地址，否則會影響收寄、運輸、投遞及退回處理。",
    tags: ["審題稿v1", "郵件處理規則", "封面"],
  }),
  choice({
    law_area: "郵件處理規則",
    question: "關於禁寄或限寄物品之規範目的，下列何者較正確？",
    options: {
      A: "維護人員安全、郵件安全及公共利益",
      B: "增加郵件重量",
      C: "免除寄件人所有義務",
      D: "使郵件無法追蹤",
    },
    answer: "A",
    explanation: "禁寄、限寄物品規範主要是為避免危險或不適合郵寄物品危害人員、郵件或公共安全。",
    tags: ["審題稿v1", "郵件處理規則", "禁寄", "限寄"],
  }),
  choice({
    law_area: "郵件處理規則",
    question: "郵件無法投遞時，較符合處理規則精神之作法為何？",
    options: {
      A: "依規定辦理招領、退回或其他後續處理",
      B: "由投遞人自行占有",
      C: "一律立即銷毀",
      D: "一律改寄給任何鄰居",
    },
    answer: "A",
    explanation: "郵件無法投遞時，應依規定辦理招領、退回或其他法定後續程序，不得任意處分。",
    tags: ["審題稿v1", "郵件處理規則", "無法投遞"],
  }),
  choice({
    law_area: "郵務營業規章",
    question: "窗口收寄郵件時，下列何者通常是判斷資費與服務類型的重要因素？",
    options: {
      A: "郵件種類、重量、寄達地及附加服務",
      B: "寄件人職業",
      C: "櫃員個人喜好",
      D: "收件人是否喜歡郵票",
    },
    answer: "A",
    explanation: "資費與服務類型通常須依郵件種類、重量、寄達地及是否使用附加服務判斷。",
    tags: ["審題稿v1", "郵務營業規章", "資費"],
  }),
  choice({
    law_area: "郵務營業規章",
    question: "掛號郵件與平常郵件之主要差異，較可能在於下列何者？",
    options: {
      A: "掛號郵件通常有較完整之收據、查詢或投遞紀錄",
      B: "掛號郵件不得查詢",
      C: "掛號郵件一定不需收件人或代收人簽收",
      D: "掛號郵件與平常郵件完全沒有差異",
    },
    answer: "A",
    explanation: "掛號郵件通常具有收據、查詢、投遞或簽收紀錄等較高程度的處理要求。",
    tags: ["審題稿v1", "郵務營業規章", "掛號"],
  }),
  choice({
    law_area: "郵務營業規章",
    question: "關於報值或保價性質之郵務服務，下列何者較符合考點？",
    options: {
      A: "通常涉及價值申報、資費及責任範圍之判斷",
      B: "不論價值高低均不得申報",
      C: "只要口頭表示即可免除所有程序",
      D: "與郵件遺失、毀損責任完全無關",
    },
    answer: "A",
    explanation: "報值或保價性質服務通常會連結價值申報、資費計算及郵件滅失毀損時的責任範圍。",
    tags: ["審題稿v1", "郵務營業規章", "報值", "保價"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    question: "郵政儲金業務與一般郵務服務之主要差異為何？",
    options: {
      A: "郵政儲金涉及帳戶與金錢管理",
      B: "郵政儲金只是信函投遞",
      C: "郵政儲金不得保存交易紀錄",
      D: "郵政儲金不涉及客戶權益",
    },
    answer: "A",
    explanation: "郵政儲金業務涉及帳戶、存提款、交易紀錄及客戶資金安全，與一般郵件收寄不同。",
    tags: ["審題稿v1", "郵政儲金匯兌法", "儲金"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    question: "關於郵政匯兌業務，下列何者較正確？",
    options: {
      A: "涉及款項移轉、身分確認與交易紀錄",
      B: "與金錢移轉無關",
      C: "不需任何紀錄",
      D: "只適用於郵件封面書寫",
    },
    answer: "A",
    explanation: "郵政匯兌業務以款項移轉為核心，通常須注意身分確認、交易正確性與紀錄保存。",
    tags: ["審題稿v1", "郵政儲金匯兌法", "匯兌"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    question: "若郵政儲金帳戶出現異常交易，較適當之處理方向為何？",
    options: {
      A: "依規定確認身分、交易紀錄及必要控管措施",
      B: "完全不留紀錄",
      C: "由任一第三人任意領取",
      D: "視為普通郵件退回",
    },
    answer: "A",
    explanation: "異常交易涉及客戶資金安全，應確認身分、查核交易紀錄並採取必要控管措施。",
    tags: ["審題稿v1", "郵政儲金匯兌法", "異常交易"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    question: "簡易人壽保險制度之主要目的，較接近下列何者？",
    options: {
      A: "提供較普及、簡易之人身保險服務",
      B: "處理郵件無法投遞問題",
      C: "規範郵件封面格式",
      D: "排除保險契約之適用",
    },
    answer: "A",
    explanation: "簡易人壽保險制度重點在提供較普及、簡易的人身保險服務，仍須依保險契約及特別法規判斷。",
    tags: ["審題稿v1", "簡易人壽保險法", "制度目的"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    question: "簡易人壽保險契約中，判斷保險給付通常應先確認何者？",
    options: {
      A: "契約有效、保險事故、受益人資格及限制事由",
      B: "郵件是否掛號",
      C: "郵資是否足額",
      D: "信封是否完整",
    },
    answer: "A",
    explanation: "保險給付判斷通常須先確認契約是否有效、保險事故是否發生、受益人資格與是否有除外或限制事由。",
    tags: ["審題稿v1", "簡易人壽保險法", "保險給付"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    question: "關於要保人、被保險人與受益人，下列何者較正確？",
    options: {
      A: "三者身分及權利義務應依保險契約與法規判斷",
      B: "三者永遠必須是同一人",
      C: "受益人不得請求任何保險給付",
      D: "被保險人與保險事故無關",
    },
    answer: "A",
    explanation: "要保人、被保險人與受益人可能相同也可能不同，其權利義務應依契約與法規判斷。",
    tags: ["審題稿v1", "簡易人壽保險法", "保險契約"],
  }),
  choice({
    career_level: "professional_1_to_operations",
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "若題目要求判斷郵件事故責任，最適合的第一步為何？",
    options: {
      A: "確認郵件種類、交寄方式、附加服務與處理紀錄",
      B: "直接認定郵局必然負全部責任",
      C: "直接認定寄件人必然無權請求",
      D: "完全不看交寄紀錄",
    },
    answer: "A",
    explanation: "郵件事故責任判斷須先確認郵件種類、交寄方式、是否有附加服務及相關處理紀錄。",
    tags: ["審題稿v1", "營運職", "郵件事故"],
  }),
  choice({
    career_level: "professional_1_to_operations",
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "關於個人資料與金融交易紀錄之處理，下列何者較正確？",
    options: {
      A: "應限制未授權人員查閱或揭露",
      B: "可供任何員工任意公開",
      C: "不需保存任何交易紀錄",
      D: "與郵政儲金匯兌業務無關",
    },
    answer: "A",
    explanation: "涉及個人資料與金融交易紀錄時，應限制未授權查閱或揭露，以維護客戶權益與交易安全。",
    tags: ["審題稿v1", "營運職", "個資", "交易紀錄"],
  }),
  choice({
    career_level: "professional_1_to_operations",
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "若法規修正後各分局仍使用舊表單，較可能產生何種風險？",
    options: {
      A: "作業標準不一致與民眾混淆",
      B: "郵件重量必然下降",
      C: "郵資一律免收",
      D: "保險契約自動消滅",
    },
    answer: "A",
    explanation: "法規或流程修正後仍使用舊表單，容易造成作業標準不一致、判斷錯誤及民眾混淆。",
    tags: ["審題稿v1", "營運職", "作業標準"],
  }),
  choice({
    career_level: "professional_1_to_operations",
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "若保險事故發生後有多名受益人主張權利，較適當之處理方向為何？",
    options: {
      A: "依契約、受益人指定及相關法規確認給付對象",
      B: "由櫃員任意選擇其中一人",
      C: "一律拒絕給付",
      D: "視為郵件招領事件",
    },
    answer: "A",
    explanation: "多名受益人主張權利時，應回到契約、受益人指定及相關法規確認給付對象與比例。",
    tags: ["審題稿v1", "營運職", "受益人"],
  }),
  choice({
    career_level: "professional_1_to_operations",
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "關於高風險交易與一般交易分流，下列何者較符合內控目的？",
    options: {
      A: "一般案件快速處理，高風險案件加強驗證",
      B: "所有案件均不需驗證",
      C: "高風險案件優先忽略紀錄",
      D: "一般案件不得受理",
    },
    answer: "A",
    explanation: "依風險分流可兼顧效率與安全，一般案件快速處理，高風險案件則加強身分、紀錄或其他驗證。",
    tags: ["審題稿v1", "營運職", "內控", "高風險交易"],
  }),
];

type CompactPostalQuestion = {
  career_level?: PostalCareerLevel;
  law_area: PostalLawArea;
  difficulty?: 1 | 2 | 3;
  question: string;
  correct: string;
  wrong: [string, string, string];
  explanation: string;
  article_no?: string;
  tags?: string[];
};

function compactChoice(row: CompactPostalQuestion): PostalRuleQuestion {
  return choice({
    career_level: row.career_level,
    law_area: row.law_area,
    difficulty: row.difficulty ?? 2,
    question: row.question,
    options: {
      A: row.correct,
      B: row.wrong[0],
      C: row.wrong[1],
      D: row.wrong[2],
    },
    answer: "A",
    explanation: row.explanation,
    article_no: row.article_no,
    tags: ["審題稿v2", ...(row.tags ?? [row.law_area])],
  });
}

const approvedReviewQuestionsV2: PostalRuleQuestion[] = ([
  {
    law_area: "郵政法",
    difficulty: 2,
    question: "題目若問「郵件秘密」之保護，下列哪一組答題方向最完整？",
    correct: "不得任意拆閱、洩漏或不當處理郵件內容",
    wrong: ["只要郵件已交寄即可公開內容", "只保護包裹外觀，不保護內容", "只限制收件人，不限制處理人員"],
    explanation: "郵件秘密重點在郵件處理過程中對內容與相關資訊的保護，不得任意拆閱或洩漏。",
    tags: ["郵政法", "郵件秘密"],
  },
  {
    law_area: "郵政法",
    difficulty: 2,
    question: "下列何者最可能違反郵政制度中避免公眾誤認之要求？",
    correct: "未經授權使用近似郵政機構名稱招攬信件遞送",
    wrong: ["依法查詢郵件投遞進度", "寄件人保存收據", "收件人要求補發通知"],
    explanation: "容易使公眾誤認為郵政機構或郵政服務者，通常涉及名稱、專營或制度保護問題。",
    tags: ["郵政法", "名稱", "專營"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "某業者標榜「官方郵政代收中心」但未取得授權，考試上最應先判斷何者？",
    correct: "是否使一般民眾誤認其為郵政機構或經授權業者",
    wrong: ["業者廣告顏色是否醒目", "業者是否提供冷氣", "業者是否只收現金"],
    explanation: "此類題目應優先判斷公眾誤認、郵政名稱使用及專營秩序，而不是營業外觀細節。",
    tags: ["郵政法", "案例題"],
  },
  {
    law_area: "郵政法",
    difficulty: 2,
    question: "郵件處理人員因好奇查看他人信件內容，最接近下列何種考點？",
    correct: "郵件秘密及郵件處理安全",
    wrong: ["郵政儲金利率", "簡易人壽保險受益人順位", "英文閱讀測驗"],
    explanation: "任意查看信件內容通常直接連結郵件秘密與依法處理郵件之義務。",
    tags: ["郵政法", "郵件處理"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "數字敏感題：若題目出現「主管機關公告之期限、金額或罰鍰」，作答時最適當的態度為何？",
    correct: "依題目所給法規版本與條文數字判斷，不憑印象猜測",
    wrong: ["一律選最大數字", "一律選最小數字", "只看選項文字長短"],
    explanation: "郵政法規的數字題常考期限、金額、罰鍰或重量限制，必須依當年度法規版本判斷。",
    tags: ["數字題", "法規版本"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 2,
    question: "寄件人交寄內裝物性質特殊之郵件時，下列何者較符合處理規則精神？",
    correct: "應依禁寄、限寄或特殊收寄規定判斷是否可收寄",
    wrong: ["只要寄件人願意付費即一律收寄", "郵局不得詢問內裝物", "一律以普通信函處理"],
    explanation: "特殊物品可能涉及安全或禁限寄規範，應先確認其性質與適用規則。",
    tags: ["郵件處理規則", "禁寄", "限寄"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "數字敏感題：若題目問某類郵件之重量、尺寸或期間限制，最可能的命題目的為何？",
    correct: "測驗考生是否能依郵件種類正確套用數字限制",
    wrong: ["測驗考生是否會猜選項", "測驗考生是否知道英文單字", "測驗考生是否能背誦民法條文"],
    explanation: "郵件處理規則與營業規章常以重量、尺寸、期限或通知期間設計數字題。",
    tags: ["數字題", "郵件處理規則"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 2,
    question: "郵件因地址不明無法投遞，最適合的處理方向為何？",
    correct: "依規定辦理查詢、招領、退回或其他後續程序",
    wrong: ["立即由投遞人取得所有權", "一律交給鄰居", "一律改寄海外"],
    explanation: "無法投遞郵件仍須依處理規則辦理，不得任意處分。",
    tags: ["郵件處理規則", "無法投遞"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "某郵件封面同時有收件人姓名錯誤與地址不完整，最應先判斷何者？",
    correct: "是否仍足以辨識收件人與投遞地址",
    wrong: ["郵票顏色是否一致", "寄件人字跡是否漂亮", "信封是否為白色"],
    explanation: "封面資料判斷重點在能否辨識與完成投遞，而非形式外觀。",
    tags: ["郵件處理規則", "封面"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "數字敏感題：某題組列出郵件保管 7 日、15 日、30 日等選項，最正確的解題方法為何？",
    correct: "先確認郵件種類與題目指定的法規版本，再比對相應期間",
    wrong: ["一律選 7 日", "一律選 30 日", "依選項順序輪流作答"],
    explanation: "保管、招領、退回等期間可能因郵件種類而不同，必須先分類再套數字。",
    tags: ["數字題", "期間", "郵件處理規則"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 2,
    question: "郵務窗口判斷資費時，最應優先掌握下列哪一組因素？",
    correct: "郵件種類、重量、尺寸、寄達地與附加服務",
    wrong: ["寄件人年齡、衣著、交通方式", "收件人職稱、星座、電話品牌", "櫃台當日心情"],
    explanation: "郵務資費通常與郵件種類、重量尺寸、寄達地及附加服務相關。",
    tags: ["郵務營業規章", "資費"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "數字敏感題：若題目同時出現重量級距與附加服務費，最適合的作答順序為何？",
    correct: "先判斷郵件種類與重量級距，再加計附加服務",
    wrong: ["先選最大金額", "先選最小金額", "完全不看重量"],
    explanation: "資費題常需分步計算，先確認種類與級距，再處理掛號、報值、快捷等附加服務。",
    tags: ["數字題", "資費", "郵務營業規章"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 2,
    question: "下列何者最能區分掛號郵件與平常郵件？",
    correct: "掛號郵件通常具有收據、查詢及投遞紀錄",
    wrong: ["掛號郵件一定免費", "平常郵件一定不得投遞", "兩者完全沒有處理差異"],
    explanation: "掛號服務的特色在處理紀錄、查詢及交付證明程度較高。",
    tags: ["郵務營業規章", "掛號"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "顧客要求寄送高價物品並主張提高保障，窗口最應提醒其注意何者？",
    correct: "是否適用報值、保價或其他附加服務及其責任範圍",
    wrong: ["只要口頭聲明即可完全保障", "郵局一律不受理高價物品", "高價物品必然免資費"],
    explanation: "高價物品常涉及報值、保價、資費與責任範圍，不能只憑口頭聲明。",
    tags: ["郵務營業規章", "報值", "保價"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "數字敏感題：某題問「快捷、限時、掛號」不同服務之資費差異，最合理的判斷方式為何？",
    correct: "分別依服務種類、重量與寄達地套用資費表",
    wrong: ["所有服務資費必然相同", "只看郵票圖案", "一律選最便宜者"],
    explanation: "不同附加服務可能有不同資費與適用條件，必須分別判斷。",
    tags: ["數字題", "附加服務", "資費"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 2,
    question: "郵政儲金業務最核心的法律風險通常與下列何者有關？",
    correct: "帳戶管理、身分確認、交易紀錄與客戶資金安全",
    wrong: ["郵票收藏價值", "信封顏色", "寄件人作文能力"],
    explanation: "儲金業務涉及金錢與帳戶，重點在身分、紀錄、安全與客戶權益。",
    tags: ["郵政儲金匯兌法", "儲金"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "數字敏感題：若題目問儲金或匯兌之限額、期間或手續費，下列何者較正確？",
    correct: "應依題目指定法規版本與相關公告數字判斷",
    wrong: ["所有限額永遠相同", "數字題一律不會考", "只需看民法規定"],
    explanation: "儲金匯兌題常可能涉及限額、期間、手續費或公告數字，應依最新有效規範判斷。",
    tags: ["數字題", "郵政儲金匯兌法"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 2,
    question: "關於郵政匯兌業務之處理，下列何者較符合制度目的？",
    correct: "確保款項移轉正確、紀錄完整並保護客戶權益",
    wrong: ["不得留下任何紀錄", "可由任意第三人代領所有款項", "與金錢移轉無關"],
    explanation: "匯兌業務涉及款項移轉，應重視正確性、紀錄與安全。",
    tags: ["郵政儲金匯兌法", "匯兌"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "若櫃員發現交易資料與客戶身分資料不一致，較適當的處理方向為何？",
    correct: "暫緩或加強確認，依規定查核身分與交易資料",
    wrong: ["直接忽略差異", "由其他排隊民眾代為確認", "立即刪除所有紀錄"],
    explanation: "身分與交易資料不一致時，應加強確認並依規定處理，避免交易風險。",
    tags: ["郵政儲金匯兌法", "身分確認"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "數字敏感題：某題列出每日交易次數或金額上限，最容易出錯的原因為何？",
    correct: "未確認題目適用的業務類型與法規版本",
    wrong: ["選項太短", "題目使用繁體中文", "答案一定在第一選項"],
    explanation: "金額或次數上限常與業務類型、帳戶種類或公告規定有關，不能只憑印象。",
    tags: ["數字題", "限額", "交易"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 2,
    question: "簡易人壽保險給付判斷，最應優先確認下列哪一組事項？",
    correct: "契約有效、保險事故、受益人資格與限制事由",
    wrong: ["郵件重量與投遞區域", "郵票樣式與信封顏色", "寄件人是否使用掛號"],
    explanation: "保險給付應回到契約、事故、受益人及限制事由判斷。",
    tags: ["簡易人壽保險法", "保險給付"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "數字敏感題：若題目問保險金額、保費或給付期間，下列何者最正確？",
    correct: "依契約內容與簡易人壽保險相關規定核對數字",
    wrong: ["一律依郵件重量判斷", "一律依郵票面額判斷", "一律不需看契約"],
    explanation: "保險數字題通常須同時看契約內容與法規限制，不能用郵務資費邏輯處理。",
    tags: ["數字題", "簡易人壽保險法", "保險金額"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 2,
    question: "要保人、被保險人與受益人之關係，下列何者較正確？",
    correct: "三者可能相同也可能不同，應依契約與法規判斷",
    wrong: ["三者必然永遠相同", "受益人永遠不能請求給付", "被保險人與保險事故無關"],
    explanation: "保險契約中的角色可能分離，應依契約指定及相關規定判斷。",
    tags: ["簡易人壽保險法", "保險契約"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "多名受益人同時主張保險給付時，最適合的處理方向為何？",
    correct: "依契約指定、受益比例與相關法規確認給付對象",
    wrong: ["由櫃員任意選擇一人", "一律拒絕給付", "視為郵件退回事件"],
    explanation: "多名受益人情境應回到契約指定、比例與法規限制處理。",
    tags: ["簡易人壽保險法", "受益人"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "數字敏感題：保險題目同時出現年齡、期間與金額時，最適合的解題方式為何？",
    correct: "分別確認投保資格、契約期間與給付或保費限制",
    wrong: ["只看年齡最大者", "只看金額最高者", "直接套用郵件處理規則"],
    explanation: "保險數字題常同時涉及年齡、期間、金額等限制，應逐項拆解。",
    tags: ["數字題", "年齡", "期間", "金額"],
  },
] satisfies CompactPostalQuestion[]).map(compactChoice);

const approvedNumericQuestionsV3: PostalRuleQuestion[] = ([
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "數字題：郵政法規題目同時出現「罰鍰金額」與「主管機關命令改善期限」時，最應先判斷何者？",
    correct: "先確認題目問的是處罰金額、改善期限或二者間的先後關係",
    wrong: ["直接選金額最高者", "只看題目最後一個數字", "一律認為期限比罰鍰不重要"],
    explanation: "數字題常故意混合金額與期限。作答時應先判斷命題焦點，再回到法規版本與條文類型核對。",
    tags: ["數字題", "郵政法", "罰鍰", "期限"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "數字題：若選項分別列出不同罰鍰區間，下列何者是較穩定的作答方法？",
    correct: "辨識違規類型後，對照該類違規所屬罰鍰區間",
    wrong: ["只選最低罰鍰", "只選最高罰鍰", "看到罰鍰二字即判斷為刑罰"],
    explanation: "罰鍰區間必須與違規類型連動，不能只靠數字大小猜答案。",
    tags: ["數字題", "郵政法", "罰鍰"],
  },
  {
    law_area: "郵政法",
    difficulty: 2,
    question: "數字題：題目問某期間是否已屆滿，最容易漏掉的判斷是什麼？",
    correct: "期間起算點與是否有公告、通知或送達等起算事實",
    wrong: ["只看期間長短", "只看月份名稱", "只看金額大小"],
    explanation: "期間題的核心不只是天數，還包括從何時起算，以及題目事實是否已發生起算事由。",
    tags: ["數字題", "郵政法", "期間", "起算"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "數字題：郵政專營或名稱使用題若加入金額選項，最合理的解題順序為何？",
    correct: "先判斷是否構成違反專營或名稱使用規範，再確認可能法律效果",
    wrong: ["先計算營業額再決定是否違法", "只要金額小就一定不違法", "只要有廣告費就一定成立"],
    explanation: "此類題目的第一層仍是構成要件，金額通常是法律效果或情節判斷的一部分。",
    tags: ["數字題", "郵政法", "專營", "法律效果"],
  },
  {
    law_area: "郵政法",
    difficulty: 2,
    question: "數字題：遇到「每日、每月、每件、每次」等文字時，最應注意什麼？",
    correct: "注意計算單位不同，不能把次數、件數與期間混為一談",
    wrong: ["所有單位都可互換", "只要數字相同答案就相同", "每日一定等於每件"],
    explanation: "考試常用單位差異製造陷阱。每日、每月、每件、每次代表不同計算基礎。",
    tags: ["數字題", "郵政法", "計算單位"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "數字題：若題目給出新舊法規不同數字，下列何者較正確？",
    correct: "依題目指定施行日期或最新公告版本判斷",
    wrong: ["永遠使用舊法數字", "永遠使用老師印象中的數字", "只選看起來最整齊的數字"],
    explanation: "郵政法規數字常受修正或公告影響。正式作答應確認題目指定版本與施行日期。",
    tags: ["數字題", "郵政法", "法規版本"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "數字題：郵件處理題同時出現重量、尺寸與保管期間，最適合先判斷何者？",
    correct: "先判斷郵件種類，再分別核對重量、尺寸與期間限制",
    wrong: ["只看重量最大者", "只看保管期間最長者", "重量與尺寸永遠不影響處理方式"],
    explanation: "重量、尺寸與期間限制通常要先依郵件種類分類後才有意義。",
    tags: ["數字題", "郵件處理規則", "重量", "尺寸", "期間"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "數字題：選項列出不同保管日數時，下列何者最能避免誤答？",
    correct: "確認郵件是否已通知、是否招領、是否退回，以及期間起算點",
    wrong: ["看到日數最長就選", "一律從寄件日開始算", "一律從考試日期開始算"],
    explanation: "保管期間題常考通知、招領、退回與起算點，不能只背孤立日數。",
    tags: ["數字題", "郵件處理規則", "保管期間", "起算"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 2,
    question: "數字題：包裹或郵件重量超過限制時，最可能影響下列何者？",
    correct: "是否得按原種類收寄及其資費或處理方式",
    wrong: ["收件人姓名是否有效", "郵票顏色是否正確", "保險受益人順位"],
    explanation: "重量限制通常影響郵件種類、收寄可否、資費及後續處理。",
    tags: ["數字題", "郵件處理規則", "重量"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "數字題：題目給出「通知後若干日內未領取」的情境，最應連結哪一類考點？",
    correct: "無法投遞郵件、招領、保管及退回程序",
    wrong: ["郵政儲金利率", "簡易壽險保費", "英文克漏字"],
    explanation: "通知後期間屆滿通常與招領保管及退回流程有關。",
    tags: ["數字題", "郵件處理規則", "通知", "退回"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 2,
    question: "數字題：若題目問郵件查詢或補償期間，下列何者較正確？",
    correct: "應先區分郵件種類與查詢、補償所適用的不同期間",
    wrong: ["所有郵件期間完全相同", "補償期間一定等於保管期間", "只要逾期仍一定可全額請求"],
    explanation: "查詢、補償、保管各有不同制度目的，期間不可任意混用。",
    tags: ["數字題", "郵件處理規則", "查詢", "補償"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "數字題：題目列出多個尺寸長寬高數字時，最應注意什麼？",
    correct: "尺寸限制可能包含單邊限制與長寬高合計限制",
    wrong: ["只看最小邊", "只看郵件顏色", "尺寸一定不影響收寄"],
    explanation: "尺寸題常同時考單邊與合計限制，需逐項核對。",
    tags: ["數字題", "郵件處理規則", "尺寸"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "數字題：窗口資費題同時出現重量級距與附加服務，最合理的計算順序為何？",
    correct: "先確認基本郵件種類與重量級距，再加計附加服務費用",
    wrong: ["先加所有附加費再決定郵件種類", "只看附加服務名稱", "重量級距不影響資費"],
    explanation: "資費題通常先有基本資費，再依掛號、快捷、報值等附加服務加計。",
    tags: ["數字題", "郵務營業規章", "資費", "重量級距"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "數字題：報值或保價郵件題目出現金額時，下列何者最重要？",
    correct: "確認申報價值、服務種類及賠償上限是否相互對應",
    wrong: ["金額越高一定越安全且無上限", "報值金額與賠償範圍毫無關係", "一律視為普通信函"],
    explanation: "報值、保價與賠償上限具有連動關係，不能只看單一金額。",
    tags: ["數字題", "郵務營業規章", "報值", "保價", "賠償"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 2,
    question: "數字題：快捷、限時、掛號等服務若有不同費率，最應先判斷什麼？",
    correct: "顧客選擇的是哪一種郵務服務及是否另加附加服務",
    wrong: ["一律用最低費率", "一律用最高費率", "只看收件人姓氏"],
    explanation: "不同服務有不同資費邏輯，須先分類服務種類。",
    tags: ["數字題", "郵務營業規章", "快捷", "掛號", "資費"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "數字題：顧客要求寄送高價物品，選項出現多個保障金額時，應如何判斷？",
    correct: "確認是否選用可提高保障的服務，並核對申報金額與規章限制",
    wrong: ["只要物品昂貴就自動全額保障", "未申報也必然依最高金額賠償", "與郵務營業規章無關"],
    explanation: "高價物品不當然全額保障，通常需選擇適當附加服務並符合規章限制。",
    tags: ["數字題", "郵務營業規章", "保障金額"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 2,
    question: "數字題：郵務窗口遇到資費表版本不同時，最適當處理方式為何？",
    correct: "依現行公告資費表與服務種類核對",
    wrong: ["依舊表永遠不變", "由窗口自行決定金額", "只看顧客願意付多少"],
    explanation: "資費具有公告與版本問題，考試上應以現行規章或題目指定版本為準。",
    tags: ["數字題", "郵務營業規章", "資費表", "版本"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "數字題：若題目同時問郵資、掛號費與報值費，下列何者較正確？",
    correct: "三者可能分屬基本資費與附加費，應分項計算",
    wrong: ["三者必定只能擇一", "掛號費會自動取代所有郵資", "報值費與申報價值無關"],
    explanation: "郵務資費常由基本郵資與多項附加費構成，需分項處理。",
    tags: ["數字題", "郵務營業規章", "郵資", "掛號", "報值"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "數字題：郵政儲金題若同時出現存款限額與交易次數，最適合先判斷什麼？",
    correct: "先區分是帳戶餘額限制、單筆交易限制或每日交易限制",
    wrong: ["所有限制都屬同一概念", "只看最大金額", "交易次數永遠不重要"],
    explanation: "儲金與匯兌數字題常混合餘額、單筆、每日或次數限制，必須先分類。",
    tags: ["數字題", "郵政儲金匯兌法", "限額", "交易次數"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "數字題：匯兌題出現手續費、匯款金額與退匯金額時，最應避免何種錯誤？",
    correct: "避免把匯款本金、手續費與可退還金額混為一談",
    wrong: ["三者一定完全相同", "手續費一定等於本金", "退匯必然沒有任何規範"],
    explanation: "匯兌題的數字往往有不同性質，需區分本金、費用與退還範圍。",
    tags: ["數字題", "郵政儲金匯兌法", "匯兌", "手續費"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 2,
    question: "數字題：題目問存款利息或費用時，下列何者較正確？",
    correct: "應依業務種類、公告利率或費用標準判斷",
    wrong: ["所有帳戶利率完全相同", "利息永遠不可能變動", "只依郵件重量判斷"],
    explanation: "儲匯業務的數字常涉及公告標準與業務類型，不可套用郵件處理規則。",
    tags: ["數字題", "郵政儲金匯兌法", "利息", "費用"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "數字題：若客戶短時間內多次交易且金額接近門檻，較可能考什麼？",
    correct: "交易安全、異常交易辨識及必要確認程序",
    wrong: ["郵件封面書寫", "保險受益人順位", "郵票圖案"],
    explanation: "多次、接近門檻的交易情境常用來測風險控管與身分確認。",
    tags: ["數字題", "郵政儲金匯兌法", "異常交易", "門檻"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 2,
    question: "數字題：儲金與匯兌題若出現「單筆」與「累計」兩種金額，應如何處理？",
    correct: "分別判斷單筆限制與一定期間內累計限制",
    wrong: ["單筆永遠等於累計", "只看第一筆交易", "只看最後一筆交易"],
    explanation: "單筆與累計是不同計算基礎，考試常以此製造陷阱。",
    tags: ["數字題", "郵政儲金匯兌法", "單筆", "累計"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "數字題：題目給出不同交易日期與金額時，最應先建立什麼？",
    correct: "建立時間順序，確認每筆交易是否落在同一計算期間",
    wrong: ["只加總所有看得到的數字", "只看最大一筆", "忽略日期"],
    explanation: "是否屬同一日、同一月或同一計算期間，會影響交易限制判斷。",
    tags: ["數字題", "郵政儲金匯兌法", "日期", "期間"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "數字題：簡易人壽保險題同時出現投保年齡、保險金額與保險期間，應如何拆解？",
    correct: "分別判斷投保資格、金額限制與契約期間",
    wrong: ["只看保險金額最高者", "只看年齡最小者", "直接套用郵件重量規則"],
    explanation: "壽險數字題常同時有年齡、金額與期間，須逐項分析。",
    tags: ["數字題", "簡易人壽保險法", "年齡", "金額", "期間"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "數字題：保險給付題若出現多名受益人與比例，最應注意什麼？",
    correct: "依契約指定與受益比例計算各受益人可請求範圍",
    wrong: ["所有受益人一律平均且不能約定", "由第一位受益人取得全部", "視為郵件退回"],
    explanation: "多名受益人與比例題應回到契約指定與法規限制，不可任意分配。",
    tags: ["數字題", "簡易人壽保險法", "受益比例"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 2,
    question: "數字題：題目問保費繳納期間與保險期間，下列何者較正確？",
    correct: "兩者可能不同，應依契約內容與相關規定分別判斷",
    wrong: ["繳費期間必然等於保險期間", "保險期間只看郵件投遞日", "一律不須看契約"],
    explanation: "保費繳納期間與保險期間是不同概念，常見於數字陷阱題。",
    tags: ["數字題", "簡易人壽保險法", "保費", "保險期間"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "數字題：若題目出現等待期間、除外期間或請求期間，最適合的作答方式為何？",
    correct: "先辨識是哪一種期間，再判斷事故或請求是否落入期間內",
    wrong: ["所有期間都可互換", "只要有期間就一定不能給付", "期間與保險事故無關"],
    explanation: "保險期間題需要先分類，再判斷法律效果。",
    tags: ["數字題", "簡易人壽保險法", "等待期間", "請求期間"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 2,
    question: "數字題：保險金額與實際損害金額不一致時，最應先判斷什麼？",
    correct: "該保險給付性質與契約約定的給付標準",
    wrong: ["一定只賠實際損害", "一定只看郵資", "一定由窗口任意決定"],
    explanation: "保險給付不應直接套用郵件賠償或一般損害賠償概念，應回到契約與法規。",
    tags: ["數字題", "簡易人壽保險法", "保險金額", "給付"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "數字題：若題目同時出現保險事故日、通知日與請求日，最應先整理什麼？",
    correct: "整理時間線，確認各項期間是否已開始或屆滿",
    wrong: ["只看最後一天", "忽略事故日", "只看金額"],
    explanation: "保險題常以多個日期測期間判斷，時間線是解題關鍵。",
    tags: ["數字題", "簡易人壽保險法", "日期", "時間線"],
  },
] satisfies CompactPostalQuestion[]).map((row: CompactPostalQuestion) =>
  choice({
    career_level: row.career_level,
    law_area: row.law_area,
    difficulty: row.difficulty ?? 2,
    question: row.question,
    options: {
      A: row.correct,
      B: row.wrong[0],
      C: row.wrong[1],
      D: row.wrong[2],
    },
    answer: "A",
    explanation: row.explanation,
    tags: ["審題稿v3", ...(row.tags ?? [row.law_area])],
  }),
);

const approvedExactNumericQuestionsV4: PostalRuleQuestion[] = ([
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "依郵政法規定，小包是指寄交特定人或特定地址，重量不逾多少之小件物品？",
    correct: "一公斤",
    wrong: ["二公斤", "五百公克", "二十公斤"],
    explanation: "郵政法第4條定義小包為寄交特定人或特定地址不逾一公斤之小件物品。",
    article_no: "第4條",
    tags: ["精確數字題", "郵政法", "小包", "重量"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "依郵政法第5條之1，國內遞送普及服務所稱函件，單件重量不得逾多少？",
    correct: "二公斤",
    wrong: ["一公斤", "五公斤", "二十公斤"],
    explanation: "郵政法第5條之1列明，普及服務包含單件不逾二公斤之函件。",
    article_no: "第5條之1",
    tags: ["精確數字題", "郵政法", "普及服務", "函件"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "依郵政法第5條之1，國內遞送普及服務之包裹，單件重量及長寬高合計限制為何？",
    correct: "單件不逾二十公斤，長寬高合計不逾一百五十公分",
    wrong: ["單件不逾二公斤，長寬高合計不逾九十公分", "單件不逾一公斤，長寬高合計不逾六十公分", "單件不逾十公斤，長寬高合計不逾一百公分"],
    explanation: "郵政法第5條之1規定，包裹為單件不逾二十公斤且長寬高合計不逾一百五十公分。",
    article_no: "第5條之1",
    tags: ["精確數字題", "郵政法", "普及服務", "包裹"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "依郵政法第6條，非專營例外中，單件重量及資費門檻為何？",
    correct: "單件重量五百公克以下，或單件資費不逾十三倍基礎郵資",
    wrong: ["單件重量一公斤以下，或單件資費不逾五倍基礎郵資", "單件重量二公斤以下，或單件資費不逾十倍基礎郵資", "單件重量二十公斤以下，或單件資費不逾二十倍基礎郵資"],
    explanation: "郵政法第6條例外包含單件重量五百公克以下或單件資費不逾十三倍基礎郵資。",
    article_no: "第6條",
    tags: ["精確數字題", "郵政法", "專營", "基礎郵資"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "中華郵政公司廢止郵票時，依郵政法應於多久前公告？持有人自廢止日起多久內可換取新票？",
    correct: "一個月前公告；六個月內換取新票",
    wrong: ["十日前公告；一個月內換取新票", "十五日前公告；三個月內換取新票", "三個月前公告；五年內換取新票"],
    explanation: "郵政法第17條規定，廢止郵票應於一個月前公告，持有人自廢止日起六個月內得換取新票。",
    article_no: "第17條",
    tags: ["精確數字題", "郵政法", "郵票", "期間"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "郵件補償請求權依郵政法自郵件交寄日起，逾多久不行使而消滅？",
    correct: "六個月",
    wrong: ["十五日", "三個月", "五年"],
    explanation: "郵政法第34條規定，寄件人或收件人之補償請求權，自郵件交寄日起逾六個月不行使而消滅。",
    article_no: "第34條",
    tags: ["精確數字題", "郵政法", "補償", "消滅時效"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "郵政法規定補償金請求權，自受領補償人收到通知日起，逾多久不行使而消滅？",
    correct: "五年",
    wrong: ["六個月", "三個月", "十五日"],
    explanation: "郵政法第35條規定，補償金請求權自受領補償人收到通知之日起逾五年間不行使而消滅。",
    article_no: "第35條",
    tags: ["精確數字題", "郵政法", "補償金", "消滅時效"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "依郵政法第39條，誤收他人郵件而故意不返還者，罰鍰範圍為何？",
    correct: "新臺幣二千元以上一萬元以下",
    wrong: ["新臺幣二萬元以上十萬元以下", "新臺幣二十萬元以上一百萬元以下", "新臺幣九萬元以下"],
    explanation: "郵政法第39條規定，誤收他人郵件故意不返還者，處新臺幣二千元以上一萬元以下罰鍰。",
    article_no: "第39條",
    tags: ["精確數字題", "郵政法", "罰鍰"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "違反郵政法第6條專營規定者，依第40條罰鍰範圍為何？",
    correct: "新臺幣二十萬元以上一百萬元以下",
    wrong: ["新臺幣二千元以上一萬元以下", "新臺幣二萬元以上十萬元以下", "新臺幣三萬元以下"],
    explanation: "郵政法第40條規定，違反第6條者處新臺幣二十萬元以上一百萬元以下罰鍰，並通知停止該等行為。",
    article_no: "第40條",
    tags: ["精確數字題", "郵政法", "專營", "罰鍰"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "違反郵政法第6條之1規定，經限期改正屆期不改正者，罰鍰範圍為何？",
    correct: "新臺幣二萬元以上十萬元以下",
    wrong: ["新臺幣二千元以上一萬元以下", "新臺幣二十萬元以上一百萬元以下", "新臺幣一千萬元以下"],
    explanation: "郵政法第40條規定，違反第6條之1且屆期不改正者，處新臺幣二萬元以上十萬元以下罰鍰，並得按次處罰。",
    article_no: "第40條",
    tags: ["精確數字題", "郵政法", "罰鍰", "按次處罰"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "依郵務營業規章，信函每件重量不得逾多少？",
    correct: "二公斤",
    wrong: ["一公斤", "五公斤", "二十公斤"],
    explanation: "郵務營業規章第6條規定，信函每件重量不得逾二公斤。",
    article_no: "第6條",
    tags: ["精確數字題", "郵務營業規章", "信函", "重量"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "依郵務營業規章，信函尺寸最大限制之長、寬、厚各不得逾多少，合計以多少為限？",
    correct: "各不逾六十公分，合計以九十公分為限",
    wrong: ["各不逾九十公分，合計以一百五十公分為限", "各不逾十公分，合計以十七公分為限", "各不逾一百五十公分，合計以二十公斤為限"],
    explanation: "郵務營業規章第6條規定，信函尺寸最大限制為長寬厚各不逾六十公分，合計以九十公分為限。",
    article_no: "第6條",
    tags: ["精確數字題", "郵務營業規章", "信函", "尺寸"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "依郵務營業規章，信函尺寸最小限制不得小於多少？",
    correct: "十四公分乘九公分",
    wrong: ["十公分乘七公分", "十四公分八毫米乘十公分五毫米", "十七公分乘十公分"],
    explanation: "郵務營業規章第6條規定，信函尺寸最小限制不得小於十四公分乘九公分。",
    article_no: "第6條",
    tags: ["精確數字題", "郵務營業規章", "信函", "尺寸"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "國內明信片紙料重量依郵務營業規章應為每平方公尺多少？",
    correct: "一百八十公克以上，且不逾二百五十公克",
    wrong: ["一百公克以上，且不逾一百八十公克", "二百五十公克以上，且不逾五百公克", "五百公克以下即可"],
    explanation: "郵務營業規章第13條規定，國內明信片須以每平方公尺一百八十公克以上且不逾二百五十公克之白色紙料印製。",
    article_no: "第13條",
    tags: ["精確數字題", "郵務營業規章", "明信片", "紙料"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "國內明信片尺寸最大與最小限制，依郵務營業規章為何？",
    correct: "最大十四公分八毫米乘十公分五毫米；最小十四公分乘九公分",
    wrong: ["最大六十公分乘九十公分；最小十四公分乘九公分", "最大一百五十公分；最小十公分乘七公分", "最大十公分乘七公分；最小十四公分乘九公分"],
    explanation: "郵務營業規章第13條規定，國內明信片最大為十四公分八毫米乘十公分五毫米，最小為十四公分乘九公分。",
    article_no: "第13條",
    tags: ["精確數字題", "郵務營業規章", "明信片", "尺寸"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "印刷物每件重量限制為二公斤，但國內互寄單本書籍或寄往國外書籍可展至多少？",
    correct: "五公斤",
    wrong: ["一公斤", "七公斤", "二十公斤"],
    explanation: "郵務營業規章第32條規定，印刷物每件重量限制為二公斤；但特定書籍得展至五公斤。",
    article_no: "第32條",
    tags: ["精確數字題", "郵務營業規章", "印刷物", "書籍", "重量"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "同日同一收件人之印刷物總重量超過多少，得通知收件人至郵局領取？",
    correct: "五公斤",
    wrong: ["二公斤", "七公斤", "二十公斤"],
    explanation: "郵務營業規章第33條規定，同日同一收件人之印刷物總重量超過五公斤者，得通知至郵局領取。",
    article_no: "第33條",
    tags: ["精確數字題", "郵務營業規章", "印刷物", "重量"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "印刷物專袋每袋重量限制依郵務營業規章為何？",
    correct: "十公斤以上二十五公斤以下",
    wrong: ["二公斤以上五公斤以下", "五公斤以上十公斤以下", "二十公斤以上五十公斤以下"],
    explanation: "郵務營業規章第34條規定，印刷物專袋每袋重量限制為十公斤以上二十五公斤以下。",
    article_no: "第34條",
    tags: ["精確數字題", "郵務營業規章", "印刷物專袋", "重量"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "盲人文件每件重量依郵務營業規章不得逾多少？",
    correct: "七公斤",
    wrong: ["二公斤", "五公斤", "二十公斤"],
    explanation: "郵務營業規章第35條規定，盲人文件每件重量不得逾七公斤。",
    article_no: "第35條",
    tags: ["精確數字題", "郵務營業規章", "盲人文件", "重量"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "依郵務營業規章，國內包裹每件重量及長寬高合計限制為何？",
    correct: "重量二十公斤，長寬高三邊合計不得大於一百五十公分",
    wrong: ["重量二公斤，長寬高合計不得大於九十公分", "重量五公斤，長寬高合計不得大於六十公分", "重量七公斤，長寬高合計不得大於一百零四公分"],
    explanation: "郵務營業規章第46條規定，國內包裹每件重量限制二十公斤，最大限度為長寬高三邊合計不得大於一百五十公分。",
    article_no: "第46條",
    tags: ["精確數字題", "郵務營業規章", "國內包裹", "重量", "尺寸"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "進口國際包裹收件人未能於領取期間內領取而申請展期，至多以多久為限？",
    correct: "二個月",
    wrong: ["十五日", "一個月", "三十年"],
    explanation: "郵務營業規章第56條規定，進口國際包裹可申請展期，但至多以二個月為限。",
    article_no: "第56條",
    tags: ["精確數字題", "郵務營業規章", "國際包裹", "展期"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "保價郵件經郵局發單通知領取者，收件人應自通知之次日起多久內領取？",
    correct: "三十日內",
    wrong: ["十五日內", "一個月後始得領取", "六個月內"],
    explanation: "郵務營業規章第95條規定，保價郵件經發單通知領取者，收件人應自通知之次日起三十日內領取。",
    article_no: "第95條",
    tags: ["精確數字題", "郵務營業規章", "保價郵件", "領取期間"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "未來郵件之保管期限，依郵務營業規章最短及最長為何？",
    correct: "最短十五日，最長不逾三十年",
    wrong: ["最短三日，最長六個月", "最短一個月，最長五年", "最短十五日，最長不逾二個月"],
    explanation: "郵務營業規章第121條之2規定，未來郵件之保管期限最短十五日，最長不逾三十年。",
    article_no: "第121條之2",
    tags: ["精確數字題", "郵務營業規章", "未來郵件", "保管期限"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "存證信函留存郵局之副本，自交寄日起由郵局保存多久？",
    correct: "三年",
    wrong: ["六個月", "一個月", "五年"],
    explanation: "郵務營業規章第116條依郵件處理規則第34條第2項，存證信函副本自交寄日起由郵局保存三年，期滿後銷燬。",
    article_no: "第116條",
    tags: ["精確數字題", "郵務營業規章", "存證信函", "保存期間"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "掛號郵件招領期間，依郵件處理規則自通知招領之次日起算多久？",
    correct: "十五日",
    wrong: ["三日", "一個月", "六個月"],
    explanation: "郵件處理規則第50條規定，掛號郵件招領期間自通知招領之次日起算十五日，屆期未領者退回寄件人。",
    article_no: "第50條",
    tags: ["精確數字題", "郵件處理規則", "掛號郵件", "招領期間"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "無法投遞或不能退還寄件人之郵件，依郵件處理規則應由原寄郵局招領揭示多久？",
    correct: "一個月",
    wrong: ["十五日", "三個月", "三年"],
    explanation: "郵件處理規則第58條規定，無法投遞或不能退還寄件人之郵件，應由原寄郵局招領揭示一個月。",
    article_no: "第58條",
    tags: ["精確數字題", "郵件處理規則", "無法投遞", "招領揭示"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "掛號郵件查詢期限依郵件處理規則原則上自交寄之次日起算多久？",
    correct: "六個月",
    wrong: ["十五日", "三個月", "五年"],
    explanation: "郵件處理規則第60條規定，掛號郵件查詢期限自交寄之次日起算六個月。",
    article_no: "第60條",
    tags: ["精確數字題", "郵件處理規則", "查詢期限"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "依郵件處理規則，郵件經查應予補償者，補償金至遲應自查詢之次日起多久內支付？",
    correct: "三個月內",
    wrong: ["十五日內", "六個月內", "五年內"],
    explanation: "郵件處理規則第63條規定，補償金至遲應自查詢之次日起三個月內為之。",
    article_no: "第63條",
    tags: ["精確數字題", "郵件處理規則", "補償", "期間"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "國內掛號函件全部遺失或被竊之補償金，依郵件處理規則每件為多少？",
    correct: "新臺幣五百七十五元",
    wrong: ["新臺幣八百六十五元", "新臺幣一千一百五十五元", "新臺幣二千元"],
    explanation: "郵件處理規則第64條規定，國內掛號函件每件補償新臺幣五百七十五元。",
    article_no: "第64條",
    tags: ["精確數字題", "郵件處理規則", "補償金額", "掛號函件"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "國內包裹及國內快捷郵件按重量補償時，五公斤以下者補償上限為多少？",
    correct: "新臺幣五百七十五元",
    wrong: ["新臺幣八百六十五元", "新臺幣一千一百五十五元", "新臺幣三千元"],
    explanation: "郵件處理規則第65條規定，五公斤以下者補償不逾新臺幣五百七十五元。",
    article_no: "第65條",
    tags: ["精確數字題", "郵件處理規則", "包裹", "補償金額"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "國內包裹按重量補償時，超過五公斤至十公斤以下者補償上限為多少？",
    correct: "新臺幣八百六十五元",
    wrong: ["新臺幣五百七十五元", "新臺幣一千一百五十五元", "新臺幣一百五十元"],
    explanation: "郵件處理規則第65條規定，超過五公斤至十公斤以下者補償不逾新臺幣八百六十五元。",
    article_no: "第65條",
    tags: ["精確數字題", "郵件處理規則", "包裹", "補償金額"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "國內包裹按重量補償時，超過十公斤者補償上限為多少？",
    correct: "新臺幣一千一百五十五元",
    wrong: ["新臺幣五百七十五元", "新臺幣八百六十五元", "新臺幣二千元"],
    explanation: "郵件處理規則第65條規定，超過十公斤者補償不逾新臺幣一千一百五十五元。",
    article_no: "第65條",
    tags: ["精確數字題", "郵件處理規則", "包裹", "補償金額"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "以未滿十五歲之未成年人為被保險人訂立簡易人壽保險契約，死亡給付約定原則上何時始生效？",
    correct: "被保險人滿十五歲時",
    wrong: ["契約成立當日", "被保險人滿七歲時", "繳費滿三個月時"],
    explanation: "簡易人壽保險法第7條規定，除健康保險及喪葬費用給付外，其餘死亡給付約定於被保險人滿十五歲時始生效。",
    article_no: "第7條",
    tags: ["精確數字題", "簡易人壽保險法", "十五歲", "死亡給付"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "續期保險費自繳費日起多久未交付，保險人應於十日內催告？寬限期間為多久？",
    correct: "一個月未交付；三個月為寬限期間",
    wrong: ["十日未交付；一個月為寬限期間", "三個月未交付；六個月為寬限期間", "六個月未交付；二年為寬限期間"],
    explanation: "簡易人壽保險法第13條規定，續期保險費自繳費日起一個月未交付者，保險人應於十日內催告，並自當期繳費日起算三個月為寬限期間。",
    article_no: "第13條",
    tags: ["精確數字題", "簡易人壽保險法", "保險費", "寬限期間"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "簡易人壽保險契約停止效力後，要保人得於多久以內申請恢復契約效力？",
    correct: "二年以內",
    wrong: ["一個月以內", "三個月以內", "五年以內"],
    explanation: "簡易人壽保險法第14條規定，保險契約停止效力後，要保人得於二年以內申請恢復契約效力。",
    article_no: "第14條",
    tags: ["精確數字題", "簡易人壽保險法", "復效"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "保險人解除權自知有解除原因後，經過多久不行使而消滅？又自契約訂立或復效至保險事故發生日滿多久後不得解除？",
    correct: "一個月；二年",
    wrong: ["十日；三個月", "三個月；一年", "六個月；五年"],
    explanation: "簡易人壽保險法第16條規定，解除權自保險人知有解除原因後經過一個月不行使而消滅；自契約訂立或復效至事故發生日滿二年者，亦不得解除。",
    article_no: "第16條",
    tags: ["精確數字題", "簡易人壽保險法", "解除權", "期間"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "未滿十五歲被保險人於契約發生效力或復效後滿三個月未滿六個月死亡者，領受保險金額之多少？",
    correct: "四分之一",
    wrong: ["全部保險費", "保險金額之半數", "全部保險金額"],
    explanation: "簡易人壽保險法第19條規定，滿三個月未滿六個月死亡者，領受保險金額四分之一。",
    article_no: "第19條",
    tags: ["精確數字題", "簡易人壽保險法", "死亡給付", "比例"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "未滿十五歲被保險人於契約發生效力或復效後滿六個月未滿九個月死亡者，領受保險金額之多少？",
    correct: "半數",
    wrong: ["四分之一", "全部保險費", "全部保險金額"],
    explanation: "簡易人壽保險法第19條規定，滿六個月未滿九個月死亡者，領受保險金額之半數。",
    article_no: "第19條",
    tags: ["精確數字題", "簡易人壽保險法", "死亡給付", "比例"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "未滿十五歲被保險人於契約發生效力或復效後滿九個月死亡者，領受多少？",
    correct: "全部保險金額",
    wrong: ["全部保險費", "保險金額四分之一", "保險金額半數"],
    explanation: "簡易人壽保險法第19條規定，滿九個月死亡者，領受全部保險金額。",
    article_no: "第19條",
    tags: ["精確數字題", "簡易人壽保險法", "死亡給付", "比例"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "簡易人壽保險契約所發生之權利，自得為請求之日起逾多久不行使而消滅？",
    correct: "五年",
    wrong: ["一個月", "二年", "六個月"],
    explanation: "簡易人壽保險法第25條規定，由保險契約所發生之權利，自得為請求之日起逾五年不行使而消滅。",
    article_no: "第25條",
    tags: ["精確數字題", "簡易人壽保險法", "消滅時效"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "依郵政儲金匯兌法，存簿儲金每一人或每一團體得設幾戶？",
    correct: "僅得為一戶",
    wrong: ["最多二戶", "最多三戶", "不限戶數"],
    explanation: "郵政儲金匯兌法第19條規定，存簿儲金每一人或每一團體僅得為一戶。",
    article_no: "第19條",
    tags: ["精確數字題", "郵政儲金匯兌法", "存簿儲金", "戶數"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "中華郵政公司有郵政儲金匯兌法第26條所列情事之一者，罰鍰範圍為何？",
    correct: "新臺幣三十萬元以上一百五十萬元以下",
    wrong: ["新臺幣二萬元以上十萬元以下", "新臺幣五十萬元以上二百五十萬元以下", "新臺幣二十萬元以上一百萬元以下"],
    explanation: "郵政儲金匯兌法第26條規定，所列情事處新臺幣三十萬元以上一百五十萬元以下罰鍰。",
    article_no: "第26條",
    tags: ["精確數字題", "郵政儲金匯兌法", "罰鍰"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "中華郵政公司於主管機關檢查或限期提報資料時，有郵政儲金匯兌法第27條所列情事之一者，罰鍰範圍為何？",
    correct: "新臺幣五十萬元以上二百五十萬元以下",
    wrong: ["新臺幣三十萬元以上一百五十萬元以下", "新臺幣二萬元以上十萬元以下", "新臺幣二千元以上一萬元以下"],
    explanation: "郵政儲金匯兌法第27條規定，規避檢查、隱匿帳冊、無正當理由不答復或逾期提報等情事，處新臺幣五十萬元以上二百五十萬元以下罰鍰。",
    article_no: "第27條",
    tags: ["精確數字題", "郵政儲金匯兌法", "罰鍰", "檢查"],
  },
] satisfies CompactPostalQuestion[]).map((row: CompactPostalQuestion) =>
  choice({
    career_level: row.career_level,
    law_area: row.law_area,
    difficulty: row.difficulty ?? 2,
    question: row.question,
    options: {
      A: row.correct,
      B: row.wrong[0],
      C: row.wrong[1],
      D: row.wrong[2],
    },
    answer: "A",
    explanation: row.explanation,
    article_no: row.article_no,
    tags: ["審題稿v4", ...(row.tags ?? [row.law_area])],
  }),
);

const approvedPastExamVariantQuestionsV5: PostalRuleQuestion[] = ([
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "某民間業者招攬公司行號文件遞送，主張其文件每件均未逾五百公克，且收費未超過十三倍基礎郵資。依郵政法，下列判斷何者最適當？",
    correct: "應檢視是否符合第6條例外，重點在單件重量五百公克以下或單件資費不逾十三倍基礎郵資",
    wrong: ["只要是民間業者遞送文件即絕對違法", "只要重量超過一公斤才違法", "只要收費高於郵票面額即屬合法"],
    explanation: "這類題型常變形自郵政專營題。郵政法第6條例外重點是單件重量五百公克以下或單件資費不逾十三倍基礎郵資。",
    article_no: "第6條",
    tags: ["審題稿v5", "考古題變形", "郵政法", "專營", "精確數字題"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "甲持有將廢止之郵票，但看到公告後一直未處理。郵票廢止日起已逾六個月，甲才要求換取新票。依郵政法，下列何者正確？",
    correct: "中華郵政公司應於一個月前公告；持有人得自廢止日起六個月內換取新票，逾期即有問題",
    wrong: ["只要持有人仍保存郵票，十年內都可換新票", "公告前不得換票，但廢止後不限期間", "郵票廢止不需公告"],
    explanation: "郵政法第17條的考點是公告期間與換票期間：一個月前公告，廢止日起六個月內換取新票。",
    article_no: "第17條",
    tags: ["審題稿v5", "考古題變形", "郵政法", "郵票", "精確數字題"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "乙誤收鄰居郵件後明知非自己郵件仍拒絕返還。若依郵政法處理，下列罰鍰範圍何者正確？",
    correct: "新臺幣二千元以上一萬元以下",
    wrong: ["新臺幣二萬元以上十萬元以下", "新臺幣二十萬元以上一百萬元以下", "新臺幣三十萬元以上一百五十萬元以下"],
    explanation: "郵政法第39條規定，誤收他人郵件故意不返還者，處新臺幣二千元以上一萬元以下罰鍰。",
    article_no: "第39條",
    tags: ["審題稿v5", "考古題變形", "郵政法", "罰鍰", "精確數字題"],
  },
  {
    law_area: "郵政法",
    difficulty: 3,
    question: "某業者違反郵政法第6條，以遞送特定文件為營業。主管機關除通知停止該等行為外，得處何種罰鍰？",
    correct: "新臺幣二十萬元以上一百萬元以下",
    wrong: ["新臺幣二千元以上一萬元以下", "新臺幣二萬元以上十萬元以下", "新臺幣九萬元以下"],
    explanation: "郵政法第40條對違反第6條者，處新臺幣二十萬元以上一百萬元以下罰鍰，並通知停止行為。",
    article_no: "第40條",
    tags: ["審題稿v5", "考古題變形", "郵政法", "專營", "罰鍰", "精確數字題"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "考生判斷一件信函是否合格：重量1.8公斤，長寬厚合計88公分，單邊皆未超過60公分。依郵務營業規章，下列何者較正確？",
    correct: "重量未逾二公斤，且尺寸未逾長寬厚各六十公分、合計九十公分之限制",
    wrong: ["重量超過一公斤即不得作為信函", "合計超過六十公分即不得收寄", "只要是信函就完全不受重量限制"],
    explanation: "郵務營業規章第6條規定，信函重量不得逾二公斤，尺寸最大為長寬厚各不逾六十公分、合計九十公分。",
    article_no: "第6條",
    tags: ["審題稿v5", "考古題變形", "郵務營業規章", "信函", "精確數字題"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "寄件人交寄國內包裹一件，重量19公斤，長寬高合計148公分。依郵務營業規章，下列判斷何者正確？",
    correct: "未逾國內包裹每件二十公斤及長寬高合計一百五十公分限制",
    wrong: ["重量超過十公斤即一律不得收寄", "長寬高合計超過九十公分即一律不得作為國內包裹", "國內包裹重量限制為二公斤"],
    explanation: "郵務營業規章第46條規定，國內包裹每件重量限制二十公斤，長寬高三邊合計不得大於一百五十公分。",
    article_no: "第46條",
    tags: ["審題稿v5", "考古題變形", "郵務營業規章", "國內包裹", "精確數字題"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "同日同一收件人收到大量印刷物，總重量達6公斤。郵局通知收件人至郵局領取，依郵務營業規章，下列何者正確？",
    correct: "同日同一收件人之印刷物總重量超過五公斤者，得通知至郵局領取",
    wrong: ["只有超過二十公斤才得通知領取", "印刷物不論重量皆必須按址投遞", "只要超過二公斤即應銷燬"],
    explanation: "郵務營業規章第33條規定，同日同一收件人之印刷物總重量超過五公斤者，得通知收件人至郵局領取。",
    article_no: "第33條",
    tags: ["審題稿v5", "考古題變形", "郵務營業規章", "印刷物", "精確數字題"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "收件人接獲保價郵件領取通知後，經過二十五日才到郵局領取。依郵務營業規章，下列何者正確？",
    correct: "保價郵件應自通知之次日起三十日內領取，二十五日仍在期間內",
    wrong: ["保價郵件只能十五日內領取，二十五日必然逾期", "保價郵件領取期間為六個月", "保價郵件無任何領取期間限制"],
    explanation: "郵務營業規章第95條規定，保價郵件經通知領取者，收件人應自通知之次日起三十日內領取。",
    article_no: "第95條",
    tags: ["審題稿v5", "考古題變形", "郵務營業規章", "保價郵件", "精確數字題"],
  },
  {
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "某公司指定一件未來郵件於20年後寄出，並要求郵局保管。依郵務營業規章，這個期間與未來郵件保管期限的關係為何？",
    correct: "未來郵件保管期限最短十五日，最長不逾三十年，20年未超過最長限制",
    wrong: ["未來郵件最長只能保管二個月", "未來郵件最長只能保管一年", "未來郵件不設最短保管期限"],
    explanation: "郵務營業規章第121條之2規定，未來郵件保管期限最短十五日，最長不逾三十年。",
    article_no: "第121條之2",
    tags: ["審題稿v5", "考古題變形", "郵務營業規章", "未來郵件", "精確數字題"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "某掛號郵件按址投遞無法投交，郵局通知招領。收件人於通知招領之次日起第18日才領取。依郵件處理規則，下列何者正確？",
    correct: "招領期間為通知招領之次日起十五日，第18日已逾期間",
    wrong: ["招領期間為一個月，第18日一定未逾期", "招領期間為六個月", "掛號郵件沒有招領期間"],
    explanation: "郵件處理規則第50條規定，掛號郵件招領期間自通知招領之次日起算十五日，屆期未領者退回寄件人。",
    article_no: "第50條",
    tags: ["審題稿v5", "考古題變形", "郵件處理規則", "掛號郵件", "精確數字題"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "甲於交寄掛號郵件後第7個月才提出查詢。依郵件處理規則，下列何者最適當？",
    correct: "掛號郵件查詢期限自交寄之次日起算六個月，第7個月提出通常已逾查詢期限",
    wrong: ["查詢期限為十五日，第7個月仍一定有效", "查詢期限為五年", "掛號郵件不得查詢"],
    explanation: "郵件處理規則第60條規定，掛號郵件查詢期限自交寄之次日起算六個月。",
    article_no: "第60條",
    tags: ["審題稿v5", "考古題變形", "郵件處理規則", "查詢期限", "精確數字題"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "國內包裹遺失，重量為8公斤。若依郵件處理規則第65條按重量補償，其補償上限應為何？",
    correct: "新臺幣八百六十五元",
    wrong: ["新臺幣五百七十五元", "新臺幣一千一百五十五元", "新臺幣二千元"],
    explanation: "郵件處理規則第65條規定，超過五公斤至十公斤以下者，不逾新臺幣八百六十五元。",
    article_no: "第65條",
    tags: ["審題稿v5", "考古題變形", "郵件處理規則", "補償金額", "精確數字題"],
  },
  {
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "國內包裹遺失，重量為12公斤。若依郵件處理規則第65條按重量補償，其補償上限應為何？",
    correct: "新臺幣一千一百五十五元",
    wrong: ["新臺幣五百七十五元", "新臺幣八百六十五元", "新臺幣五千元"],
    explanation: "郵件處理規則第65條規定，超過十公斤者，不逾新臺幣一千一百五十五元。",
    article_no: "第65條",
    tags: ["審題稿v5", "考古題變形", "郵件處理規則", "補償金額", "精確數字題"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "甲以14歲子女為被保險人訂立簡易人壽保險契約，約定死亡給付。依簡易人壽保險法，下列何者正確？",
    correct: "除健康保險及喪葬費用給付外，其餘死亡給付約定於被保險人滿十五歲時始生效",
    wrong: ["所有死亡給付於契約成立當日立即生效", "死亡給付一律於滿十八歲始生效", "未滿十五歲者完全不得訂立任何保險契約"],
    explanation: "簡易人壽保險法第7條規定，以未滿十五歲之未成年人為被保險人時，死亡給付有滿十五歲始生效的限制。",
    article_no: "第7條",
    tags: ["審題稿v5", "考古題變形", "簡易人壽保險法", "十五歲", "精確數字題"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "要保人續期保險費自繳費日起已一個月未繳。依簡易人壽保險法，保險人應如何處理寬限期間？",
    correct: "保險人應於十日內催告，並自當期繳費日起算三個月為寬限期間",
    wrong: ["保險人可立即解除契約，無須催告", "寬限期間固定為十五日", "寬限期間自催告日起算五年"],
    explanation: "簡易人壽保險法第13條規定，續期保險費自繳費日起一個月未交付者，保險人應於十日內催告，並自當期繳費日起算三個月為寬限期間。",
    article_no: "第13條",
    tags: ["審題稿v5", "考古題變形", "簡易人壽保險法", "寬限期間", "精確數字題"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "某簡易人壽保險契約停效後，要保人於停效後1年6個月申請復效。依簡易人壽保險法，下列何者正確？",
    correct: "停效後二年以內得申請恢復契約效力，1年6個月仍在期間內",
    wrong: ["停效後三個月即不得復效", "停效後一個月即不得復效", "停效後五年內均可當然復效"],
    explanation: "簡易人壽保險法第14條規定，契約停止效力後，要保人得於二年以內申請恢復契約效力。",
    article_no: "第14條",
    tags: ["審題稿v5", "考古題變形", "簡易人壽保險法", "復效", "精確數字題"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "未滿十五歲被保險人於契約生效後5個月死亡。依簡易人壽保險法第19條，得領受保險金額之多少？",
    correct: "四分之一",
    wrong: ["全部保險費", "半數", "全部保險金額"],
    explanation: "簡易人壽保險法第19條規定，滿三個月未滿六個月死亡者，領受保險金額四分之一。",
    article_no: "第19條",
    tags: ["審題稿v5", "考古題變形", "簡易人壽保險法", "死亡給付", "精確數字題"],
  },
  {
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "未滿十五歲被保險人於契約生效後8個月死亡。依簡易人壽保險法第19條，得領受保險金額之多少？",
    correct: "半數",
    wrong: ["全部保險費", "四分之一", "全部保險金額"],
    explanation: "簡易人壽保險法第19條規定，滿六個月未滿九個月死亡者，領受保險金額之半數。",
    article_no: "第19條",
    tags: ["審題稿v5", "考古題變形", "簡易人壽保險法", "死亡給付", "精確數字題"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "甲已開立一戶存簿儲金帳戶，又主張為方便管理要再開第二戶。依郵政儲金匯兌法，下列何者正確？",
    correct: "存簿儲金每一人或每一團體僅得為一戶",
    wrong: ["每人最多可開二戶", "每人最多可開五戶", "存簿儲金完全不限戶數"],
    explanation: "郵政儲金匯兌法第19條規定，存簿儲金每一人或每一團體僅得為一戶。",
    article_no: "第19條",
    tags: ["審題稿v5", "考古題變形", "郵政儲金匯兌法", "存簿儲金", "精確數字題"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "中華郵政公司未依規定建立儲匯業務內部控制及稽核制度。依郵政儲金匯兌法第26條，罰鍰範圍為何？",
    correct: "新臺幣三十萬元以上一百五十萬元以下",
    wrong: ["新臺幣二千元以上一萬元以下", "新臺幣二萬元以上十萬元以下", "新臺幣五十萬元以上二百五十萬元以下"],
    explanation: "郵政儲金匯兌法第26條包含未依第10條建立內部控制及稽核制度，罰鍰為新臺幣三十萬元以上一百五十萬元以下。",
    article_no: "第26條",
    tags: ["審題稿v5", "考古題變形", "郵政儲金匯兌法", "內控", "罰鍰", "精確數字題"],
  },
  {
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "中華郵政公司於主管機關檢查時規避、妨礙或拒絕檢查。依郵政儲金匯兌法第27條，罰鍰範圍為何？",
    correct: "新臺幣五十萬元以上二百五十萬元以下",
    wrong: ["新臺幣三十萬元以上一百五十萬元以下", "新臺幣二萬元以上十萬元以下", "新臺幣二千元以上一萬元以下"],
    explanation: "郵政儲金匯兌法第27條規定，規避、妨礙或拒絕檢查等情事，處新臺幣五十萬元以上二百五十萬元以下罰鍰。",
    article_no: "第27條",
    tags: ["審題稿v5", "考古題變形", "郵政儲金匯兌法", "檢查", "罰鍰", "精確數字題"],
  },
] satisfies CompactPostalQuestion[]).map((row: CompactPostalQuestion) =>
  choice({
    career_level: row.career_level,
    law_area: row.law_area,
    difficulty: row.difficulty ?? 2,
    question: row.question,
    options: {
      A: row.correct,
      B: row.wrong[0],
      C: row.wrong[1],
      D: row.wrong[2],
    },
    answer: "A",
    explanation: row.explanation,
    article_no: row.article_no,
    tags: [...(row.tags ?? [row.law_area])],
  }),
);

export const seedPostalQuestions: PostalRuleQuestion[] = [
  choice({
    law_area: "郵政法",
    difficulty: 1,
    question: "關於中華郵政公司經營郵政業務之基本性質，下列何者最符合郵政法規範目的？",
    options: {
      A: "郵政服務兼具公共服務與營業服務性質，應維持普遍、公平與安全之處理原則",
      B: "郵政服務完全等同一般私人運送契約，不受特別法規範",
      C: "所有郵件均可由任何民間業者以郵政名義收寄",
      D: "郵政服務只處理國內信函，不涉及包裹或其他郵件",
    },
    answer: "A",
    explanation: "郵政法以維持郵政制度、郵件安全與普遍服務為核心。郵政服務不是單純私人運送，也不得任意以郵政名義經營。",
    tags: ["郵政法", "基本制度"],
  }),
  choice({
    law_area: "郵政法",
    question: "下列何者最可能涉及郵政法對郵件秘密與郵件安全之保護？",
    options: {
      A: "郵件處理人員任意拆閱他人信件內容",
      B: "寄件人自行保留收據",
      C: "收件人查詢投遞進度",
      D: "郵局依規定提供營業時間",
    },
    answer: "A",
    explanation: "郵件秘密與郵件安全是郵政法重要保護對象。任意拆閱他人信件內容，通常會涉及郵件秘密保護問題。",
    tags: ["郵政法", "郵件秘密"],
  }),
  choice({
    law_area: "郵政法",
    question: "關於郵政專營或郵政名稱使用，下列何者較符合考試常見判斷？",
    options: {
      A: "涉及法定專營或特許事項時，不得未經授權任意經營或使用使人誤認之名稱",
      B: "任何公司只要有運送能力，都可自稱郵政機關",
      C: "郵政名稱屬一般名詞，完全不受限制",
      D: "只要收費較低，即可排除郵政法限制",
    },
    answer: "A",
    explanation: "郵政法通常會保護郵政制度與名稱識別，避免未經授權經營或使公眾誤認。",
    tags: ["郵政法", "專營", "名稱"],
  }),
  choice({
    law_area: "郵件處理規則",
    question: "寄件人交寄郵件時，對於封面書寫與必要資訊，下列何者較正確？",
    options: {
      A: "應使收件人、地址等資訊足以辨識，避免影響收寄、運輸與投遞",
      B: "只要郵資足夠，地址完全空白亦當然可以投遞",
      C: "寄件人不得書寫任何寄件人資料",
      D: "收件人姓名錯誤時，郵局仍必須保證投遞成功",
    },
    answer: "A",
    explanation: "郵件處理重視可投遞性與安全性。封面資訊不足或錯誤，可能影響郵件處理與投遞。",
    tags: ["郵件處理規則", "交寄", "封面"],
  }),
  choice({
    law_area: "郵件處理規則",
    question: "下列何者最可能屬於郵件處理規則中對禁寄或限寄物品的規範目的？",
    options: {
      A: "避免危害人員安全、郵件安全或公共利益",
      B: "提高所有郵件的重量",
      C: "使收件人無法查詢郵件",
      D: "免除寄件人填寫任何資料的義務",
    },
    answer: "A",
    explanation: "禁寄、限寄規範通常是為了避免危險物品或不適合郵寄物品危害人員、郵件或公共安全。",
    tags: ["郵件處理規則", "禁寄", "限寄"],
  }),
  choice({
    law_area: "郵件處理規則",
    question: "郵件無法投遞時，依郵務實務與處理規則精神，下列何者通常較符合處理方向？",
    options: {
      A: "依規定辦理招領、改投、退回或其他後續處理",
      B: "一律立即銷毀，不需通知任何人",
      C: "由投遞人自行決定歸屬",
      D: "一律視為郵局所有",
    },
    answer: "A",
    explanation: "無法投遞郵件通常需依規定進行招領、退回或其他程序，不能任意處分。",
    tags: ["郵件處理規則", "無法投遞"],
  }),
  choice({
    law_area: "郵務營業規章",
    question: "關於郵務營業規章對窗口收寄作業之要求，下列何者較正確？",
    options: {
      A: "窗口應依郵件種類、重量、資費與附加服務辦理收寄",
      B: "所有郵件不論種類與重量均收取同一資費",
      C: "掛號、報值、快捷等服務不需區分",
      D: "郵務營業規章與實際收寄流程無關",
    },
    answer: "A",
    explanation: "郵務營業規章常規範郵件種類、資費、附加服務及窗口作業流程，考試常測基本分類與適用。",
    tags: ["郵務營業規章", "收寄", "資費"],
  }),
  choice({
    law_area: "郵務營業規章",
    question: "關於掛號郵件與一般郵件之差異，下列何者較符合郵務營業規章的考點？",
    options: {
      A: "掛號郵件通常具有收據、查詢或投遞紀錄等較高程度之處理要求",
      B: "掛號郵件與平常郵件完全相同，沒有任何處理差異",
      C: "掛號郵件不得查詢處理情形",
      D: "掛號郵件一定不需收件人或代收人簽收",
    },
    answer: "A",
    explanation: "掛號郵件與一般郵件的重要差異在於處理紀錄、查詢與交付證明等要求較高。",
    tags: ["郵務營業規章", "掛號"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    question: "關於郵政儲金業務，下列何者較符合郵政儲金匯兌法的制度定位？",
    options: {
      A: "郵政儲金業務受特別法規範，並應依規定辦理存款、提款及相關管理",
      B: "郵政儲金完全不受任何金融或特別法規限制",
      C: "郵政儲金帳戶可以不確認客戶身分",
      D: "郵政儲金只是一種郵件寄送服務",
    },
    answer: "A",
    explanation: "郵政儲金匯兌法規範郵政儲金與匯兌業務，涉及帳戶管理、交易安全與相關金融秩序。",
    tags: ["郵政儲金匯兌法", "儲金"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    question: "關於郵政匯兌業務，下列何者較正確？",
    options: {
      A: "匯兌業務重視款項移轉、身分確認與交易紀錄之正確性",
      B: "匯兌業務與金錢移轉無關",
      C: "匯兌業務不需要任何紀錄",
      D: "匯兌業務只適用於郵件遺失處理",
    },
    answer: "A",
    explanation: "匯兌業務本質上涉及款項移轉與交易安全，題目常從身分確認、交易紀錄與責任管理切入。",
    tags: ["郵政儲金匯兌法", "匯兌"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    question: "關於簡易人壽保險制度，下列何者較符合其基本目的？",
    options: {
      A: "提供較普及、簡易之人身保險服務，並受特別法規範",
      B: "完全排除保險契約與保險給付規範",
      C: "只處理郵件投遞，不涉及保險",
      D: "所有保險事項均可不訂契約",
    },
    answer: "A",
    explanation: "簡易人壽保險法重點在簡易、普及的人身保險制度，仍須受保險契約、給付及相關限制規範。",
    tags: ["簡易人壽保險法", "基本制度"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    question: "簡易人壽保險契約中，關於要保人、被保險人及受益人，下列何者較正確？",
    options: {
      A: "三者身分與權利義務應依保險契約及相關法規判斷",
      B: "三者必然永遠是同一人，不可能分開",
      C: "受益人不得依契約受領保險給付",
      D: "被保險人身分與保險事故無關",
    },
    answer: "A",
    explanation: "簡易人壽保險仍涉及保險契約基本角色。要保人、被保險人、受益人可能不同，應依契約與法規判斷。",
    tags: ["簡易人壽保險法", "保險契約"],
  }),
  choice({
    law_area: "郵政法",
    difficulty: 2,
    question: "若題目問及郵政人員處理郵件時應注意之義務，下列何者最能作為答題方向？",
    options: {
      A: "郵件安全、郵件秘密、依法處理與不得任意處分",
      B: "只要速度快即可，不需考慮郵件秘密",
      C: "郵件內容可任意公開以利查詢",
      D: "郵件是否遺失與郵政處理程序無關",
    },
    answer: "A",
    explanation: "郵政法及相關規則常圍繞郵件安全、秘密與依法處理。這些是選擇題與申論題都常見的基本方向。",
    tags: ["郵政法", "郵件安全", "郵件秘密"],
  }),
  choice({
    law_area: "郵務營業規章",
    difficulty: 2,
    question: "關於郵件附加服務，下列何者較可能是考試會要求區分的重點？",
    options: {
      A: "掛號、報值、限時、快捷等服務之要件、費用及處理效果",
      B: "所有附加服務均不得收費",
      C: "附加服務只是一種廣告用語，沒有作業差異",
      D: "附加服務一律免除寄件人所有責任",
    },
    answer: "A",
    explanation: "郵務營業規章常見考點是各類郵件及附加服務的適用要件、資費及處理效果。",
    tags: ["郵務營業規章", "附加服務"],
  }),
  choice({
    law_area: "郵件處理規則",
    difficulty: 2,
    question: "有關郵件查詢、補償或責任判斷，下列何者較符合郵件處理規則與郵務實務的答題方向？",
    options: {
      A: "應先確認郵件種類、交寄方式、處理紀錄及是否符合法定或約定要件",
      B: "不論郵件種類，一律給付相同補償",
      C: "只要寄件人主張遺失，郵局即無條件負全部責任",
      D: "郵件處理紀錄不得作為判斷依據",
    },
    answer: "A",
    explanation: "責任或補償判斷通常要先確認郵件種類、交寄方式、附加服務與處理紀錄，不能抽象一概而論。",
    tags: ["郵件處理規則", "查詢", "補償"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    difficulty: 2,
    question: "關於郵政儲金與一般郵務服務的差異，下列何者較正確？",
    options: {
      A: "郵政儲金涉及金錢存取與帳戶管理，應依儲金匯兌相關法規處理",
      B: "郵政儲金只是信件投遞的一種",
      C: "郵政儲金不需要任何帳戶資料",
      D: "郵政儲金完全不會涉及客戶權益保護",
    },
    answer: "A",
    explanation: "郵政儲金與郵件處理不同，核心在金錢與帳戶管理，考試常要求區分其法規依據。",
    tags: ["郵政儲金匯兌法", "帳戶"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    difficulty: 2,
    question: "若題目涉及保險事故發生後之給付，下列何者較符合簡易人壽保險的判斷順序？",
    options: {
      A: "先確認契約有效、保險事故、受益人資格及有無除外或限制事由",
      B: "只要有人申請，就一定立即給付",
      C: "保險事故與契約內容無關",
      D: "受益人資格永遠不需審查",
    },
    answer: "A",
    explanation: "保險給付通常須確認契約、事故、受益人及限制事由，不能只看是否有人提出申請。",
    tags: ["簡易人壽保險法", "保險給付"],
  }),
  choice({
    law_area: "郵政法",
    difficulty: 3,
    question: "若民間業者以容易使人誤認為郵政機構之名義招攬信件遞送業務，較可能涉及下列何種問題？",
    options: {
      A: "郵政名稱、專營或公眾誤認之管制問題",
      B: "單純民法買賣問題，與郵政法完全無關",
      C: "只涉及英文翻譯問題",
      D: "只要業者有營利目的即當然合法",
    },
    answer: "A",
    explanation: "題目若出現使人誤認郵政機構或未經授權經營郵政相關業務，應優先連結郵政名稱、專營與制度保護。",
    tags: ["郵政法", "專營", "誤認"],
  }),
  choice({
    law_area: "郵件處理規則",
    difficulty: 3,
    question: "若寄件人交寄物品性質特殊，可能危害郵件處理安全，最適當的處理方向為何？",
    options: {
      A: "依禁寄、限寄或特殊收寄規定審查，必要時拒絕收寄或要求補正",
      B: "一律照普通信件收寄",
      C: "不得詢問內容物性質",
      D: "只要包裝漂亮即可排除安全規定",
    },
    answer: "A",
    explanation: "特殊物品須依禁寄、限寄或特殊收寄規定處理，這是郵件安全與公共安全的典型考點。",
    tags: ["郵件處理規則", "特殊物品", "安全"],
  }),
  choice({
    law_area: "郵務營業規章",
    difficulty: 3,
    question: "有關郵件資費判斷，下列何者最適合作為解題步驟？",
    options: {
      A: "先判斷郵件種類，再看重量、尺寸、寄達地及附加服務",
      B: "先看寄件人心情，再決定資費",
      C: "所有郵件資費均不得因重量或服務而不同",
      D: "資費判斷與郵務營業規章無關",
    },
    answer: "A",
    explanation: "郵務資費通常與郵件種類、重量尺寸、寄達區域及附加服務有關，考試常測分類與適用。",
    tags: ["郵務營業規章", "資費"],
  }),
  choice({
    law_area: "郵政儲金匯兌法",
    difficulty: 3,
    question: "若郵政儲金帳戶出現異常交易，依法規與內控目的，下列何者較合理？",
    options: {
      A: "依規定確認身分、交易紀錄及必要控管措施",
      B: "完全不留任何紀錄",
      C: "由櫃員任意決定是否交付他人款項",
      D: "異常交易不可能發生在儲金業務",
    },
    answer: "A",
    explanation: "儲金業務涉及客戶資金安全，異常交易應重視身分確認、紀錄與控管，而非任意處理。",
    tags: ["郵政儲金匯兌法", "交易安全"],
  }),
  choice({
    law_area: "簡易人壽保險法",
    difficulty: 3,
    question: "若簡易人壽保險題目同時出現契約成立、保險事故與受益人爭議，最適當的作答順序為何？",
    options: {
      A: "先確認契約及當事人關係，再判斷事故與給付請求",
      B: "直接背誦所有條文，不需回到題目事實",
      C: "只判斷受益人姓名，不需看契約",
      D: "只看保費高低即可決定給付",
    },
    answer: "A",
    explanation: "案例型題目應先整理契約與當事人，再判斷事故、受益人及給付效果，避免跳躍作答。",
    tags: ["簡易人壽保險法", "案例判斷"],
  }),
  ...approvedReviewQuestionsV1,
  ...approvedReviewQuestionsV2,
  ...approvedNumericQuestionsV3,
  ...approvedExactNumericQuestionsV4,
  ...approvedPastExamVariantQuestionsV5,
];

export const postalSourcePacks: Record<PostalLawArea, string[]> = {
  郵政法: [
    "常見考點：郵政制度、郵件秘密、郵件安全、郵政專營、郵政名稱使用、郵件責任。",
    "出題時可設計制度目的、禁止行為、郵件保護與案例判斷。",
  ],
  郵政儲金匯兌法: [
    "常見考點：儲金、匯兌、帳戶管理、交易安全、客戶權益、異常交易處理。",
    "避免虛構精確條號；若引用條號，須在後台人工確認。",
  ],
  簡易人壽保險法: [
    "常見考點：要保人、被保險人、受益人、保險事故、保險給付、契約限制。",
    "題目應測保險關係判斷，不要混成一般郵件處理題。",
  ],
  郵件處理規則: [
    "常見考點：交寄、封面書寫、禁寄與限寄、無法投遞、查詢、補償、退回。",
    "適合做情境題，要求考生判斷處理流程。",
  ],
  郵務營業規章: [
    "常見考點：窗口收寄、郵件種類、資費、掛號、報值、快捷、附加服務。",
    "適合測郵件類型與營業流程分類。",
  ],
};

export function buildPostalRulesPrompt(input: {
  careerLevel: PostalCareerLevel;
  questionFormat: PostalQuestionFormat;
  lawArea: PostalLawArea;
  count: number;
}) {
  const careerLabel = postalCareerLevels.find((item) => item.value === input.careerLevel)?.label ?? input.careerLevel;
  const formatLabel = postalQuestionFormats.find((item) => item.value === input.questionFormat)?.label ?? input.questionFormat;

  return [
    "你是郵局內升考試的郵政法規出題老師。請只輸出 JSON，不要輸出 Markdown。",
    "目標是產生可供後台審核的練習題，不是直接宣稱正式答案已完全正確。",
    "若不能確認精確條號，article_no 請寫「依最新法規校對」，不得虛構條號。",
    "解析必須用繁體中文，且要說明為何正確選項正確、至少一個錯誤選項為何錯。",
    `職階：${careerLabel}`,
    `題型：${formatLabel}`,
    `法規分類：${input.lawArea}`,
    `題數：${input.count}`,
    `可用考點：${postalSourcePacks[input.lawArea].join(" ")}`,
    'JSON 格式：{ "questions": [ { "career_level", "question_format", "law_area", "difficulty", "question", "options", "answer", "explanation", "source_articles", "tags", "source_type", "review_status" } ] }',
    "single_choice 的 options 必須為 {A,B,C,D}，answer 必須是 A/B/C/D。",
    "source_type 固定 ai_generated_pending_review；review_status 固定 pending。",
  ].join("\n");
}

export function buildPostalExam(questions: PostalRuleQuestion[], careerLevel: PostalCareerLevel): PostalRulesExam {
  const points = questions.length ? Math.round(100 / questions.length) : 0;
  const items = questions.map((item, index) => ({
    ...shufflePostalChoiceOptions(item),
    item_no: index + 1,
    points,
  }));
  return {
    kind: "postal_rules_exam",
    title: careerLevel === "professional_2_to_1" ? "郵政法規概要練習" : "郵政法規練習",
    career_level: careerLevel,
    total_questions: items.length,
    total_points: 100,
    items,
  };
}

function shufflePostalChoiceOptions(item: PostalRuleQuestion): PostalRuleQuestion {
  if (item.question_format !== "single_choice" || !item.options) return item;
  const keys = ["A", "B", "C", "D"] as const;
  const originalAnswerKey = item.answer.trim().toUpperCase() as (typeof keys)[number];
  const correctText = item.options[originalAnswerKey];
  if (!correctText) return item;

  const shuffledTexts = shuffle(keys.map((key) => item.options?.[key] ?? ""));
  const nextOptions = {
    A: shuffledTexts[0],
    B: shuffledTexts[1],
    C: shuffledTexts[2],
    D: shuffledTexts[3],
  };
  const nextAnswer = keys.find((key) => nextOptions[key] === correctText) ?? originalAnswerKey;

  return {
    ...item,
    options: nextOptions,
    answer: nextAnswer,
  };
}

function shuffle<T>(items: T[]) {
  return [...items].sort(() => Math.random() - 0.5);
}
